name: ios_calculator
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0

environment:
  sdk: ^3.5.4

dependencies:
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.0
  flutter_launcher_icons: ^0.14.3
  flutter_native_splash: ^2.4.4
  launcher_name: ^1.0.2
  lottie: ^3.2.0
  math_expressions: ^2.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/
    - assets/animation/splash/calc.json
  fonts:
    - family: sPro
      fonts:
        - asset: assets/fonts/sfproRegular.otf

flutter_native_splash:
  color: "#000000"
  image: assets/img/splash/splash.png
  android: true
  ios: true
  android_12:
    icon_background_color: "#000000"
    image: assets/img/splash/splash.png


launcher_name:
  default: "calculator"
  fa: "ماشین حساب"
